version: '3.8'
services:
  website:
    build: 
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8081:80"
    container_name: my-website
    volumes:
      - /home/ubuntu/mywebsite:/usr/share/nginx/html
    networks:
      - website

networks:
  website:
    driver: bridge
    

