apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: test
spec:
  project: default
  source:
    repoURL: 'https://github.com/Code-By-Akhil-Thekkuveettil/practice.git'
    targetRevision: HEAD
    path: kubernetes/minikube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
