apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: akhiltofficial/saas:frontend
        volumeMounts:
        - name: appsettings-volume
          mountPath: /src/assets/config/config.json
          subPath: config.json
      volumes:
      - name: appsettings-volume
        configMap:
          name: appsettings-config
        ports:
        - containerPort: 80
        



