apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: "akhiltofficial/saas"
    argocd-image-updater.argoproj.io/update-strategy: "automatic"
spec:
  replicas: 20
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: akhiltofficial/saas:test1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: private-registry-secret
