apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-server-ingress
  namespace: calculator
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: calculator.localhost.com # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app-service
                port:
                  number: 443
  tls:
    - hosts:
        - calculator.localhost.com
      secretName: calculator-tls 
