apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-server-ingress
  namespace: calculator
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: calculator.localhost.com # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app
                port:
                  number: 80
  tls:
    - hosts:
        - calculator.localhost.com
      secretName: argocd-tls
