apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: argocd-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007 # Custom NodePort for Minikube access
